FROM ubuntu:18.04

RUN apt-get update && \
    apt-get install -y openssh-server && \
    mkdir /var/run/sshd

RUN echo 'root:root' |chpasswd

RUN sed -ri 's/^#?PermitRootLogin\s+.*/PermitRootLogin yes/' /etc/ssh/sshd_config
RUN sed -ri 's/UsePAM yes/#UsePAM yes/g' /etc/ssh/sshd_config

RUN mkdir /root/.ssh

WORKDIR tmp
COPY . .

RUN .install/core.sh
RUN .install/terraform.sh
RUN .install/azurecli.sh
RUN .install/helm.sh
RUN .install/kubectl.sh

RUN apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /tmp

WORKDIR /workspace

EXPOSE 22

CMD    ["/usr/sbin/sshd", "-D"]
